In [47]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [4]:
train_data = pd.read_csv('../data/train.csv')
test_data = pd.read_csv('../data/test_noLabel.csv')

In [6]:
print('shape of train: ', train_data.shape)
print('shape of test: ', test_data.shape)

shape of train:  (5227, 16)
shape of test:  (1307, 15)

In [7]:
train_data.head()

,ID,Contract,Dependents,DeviceProtection,InternetService,MonthlyCharges,MultipleLines,Partner,PaymentMethod,PhoneService,SeniorCitizen,TVProgram,TotalCharges,gender,tenure,Label
0,0,One year,No,No internet service,No,24.150000,Yes,Yes,Bank transfer (automatic),Yes,0,No internet service,1505.900000,Male,60,No
1,1,Month-to-month,No,No,Fiber optic,76.142284,Yes,No,Electronic check,Yes,0,No,946.581518,Female,12,Yes
2,2,Month-to-month,Yes,No internet service,No,26.200000,Yes,Yes,Electronic check,Yes,0,No internet service,1077.500000,Female,40,No
3,3,Two year,Yes,No internet service,No,24.650000,Yes,Yes,Bank transfer (automatic),Yes,0,No internet service,1138.800000,Female,45,No
4,4,Month-to-month,Yes,No internet service,No,19.150000,No,Yes,Mailed check,Yes,0,No internet service,477.600000,Male,25,No

In [22]:
train_data['DeviceProtection'].unique()

array(['No internet service', 'No', 'Yes'], dtype=object)

In [8]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5227 entries, 0 to 5226
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                5227 non-null   int64
 1   Contract          5227 non-null   object
 2   Dependents        5227 non-null   object
 3   DeviceProtection  5227 non-null   object
 4   InternetService   5227 non-null   object
 5   MonthlyCharges    5227 non-null   float64
 6   MultipleLines     5227 non-null   object
 7   Partner           5227 non-null   object
 8   PaymentMethod     5227 non-null   object
 9   PhoneService      5227 non-null   object
 10  SeniorCitizen     5227 non-null   int64
 11  TVProgram         5227 non-null   object
 12  TotalCharges      5227 non-null   float64
 13  gender            5227 non-null   object
 14  tenure            5227 non-null   int64
 15  Label             5227 non-null   object
dtypes: float64(2), int64(3), object(11)
memory usage: 653.5+ KB

In [10]:
train_data.groupby(['Label']).size()

Label
No     3280
Yes    1947
dtype: int64

In [11]:
train_X = train_data.drop(['Contract','PaymentMethod','Label'],axis=1)

In [44]:
test_X = test_data.drop(['Contract','PaymentMethod'],axis=1)

In [15]:
train_y = np.where(train_data['Label']=='Yes', 1, 0)

In [33]:
train_X['DeviceProtection']=train_X['DeviceProtection'].str.split('').str[0].str.strip()
train_X['DeviceProtection']=np.where(train_X['DeviceProtection']=='No',0,1)
train_X['TVProgram']=train_X['TVProgram'].str.split('').str[0].str.strip()
train_X['TVProgram']=np.where(train_X['TVProgram']=='No',0,1)
train_X['Dependents']=np.where(train_X['Dependents']=='No',0,1)
train_X['InternetService']=np.where(train_X['InternetService']=='No',0,1)
train_X['MultipleLines']=np.where(train_X['MultipleLines']=='No',0,1)
train_X['Partner']=np.where(train_X['Partner']=='No',0,1)
train_X['PhoneService']=np.where(train_X['PhoneService']=='No',0,1)
train_X['gender']=np.where(train_X['gender']=='No',0,1)

In [40]:
train_X

,ID,Dependents,DeviceProtection,InternetService,MonthlyCharges,MultipleLines,Partner,PhoneService,SeniorCitizen,TVProgram,TotalCharges,gender,tenure
0,0,0,1,0,24.150000,1,1,1,0,1,1505.900000,1,60
1,1,0,1,1,76.142284,1,0,1,0,1,946.581518,1,12
2,2,1,1,0,26.200000,1,1,1,0,1,1077.500000,1,40
3,3,1,1,0,24.650000,1,1,1,0,1,1138.800000,1,45
4,4,1,1,0,19.150000,0,1,1,0,1,477.600000,1,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5222,5222,0,1,0,20.750000,0,1,1,1,1,485.200000,1,23
5223,5223,0,1,0,19.900000,0,0,1,0,1,19.900000,1,1
5224,5224,1,1,1,111.750000,1,1,1,0,1,7511.300000,1,68
5225,5225,1,1,1,78.350000,1,1,1,0,1,3211.200000,1,41
5226,5226,1,1,1,105.950000,1,1,1,0,1,5341.800000,1,50

In [42]:
knn = KNeighborsClassifier()
knn.fit(train_X, train_y)

KNeighborsClassifier()

In [46]:
test_X['DeviceProtection']=test_X['DeviceProtection'].str.split('').str[0].str.strip()
test_X['DeviceProtection']=np.where(test_X['DeviceProtection']=='No',0,1)
test_X['TVProgram']=test_X['TVProgram'].str.split('').str[0].str.strip()
test_X['TVProgram']=np.where(test_X['TVProgram']=='No',0,1)
test_X['Dependents']=np.where(test_X['Dependents']=='No',0,1)
test_X['InternetService']=np.where(test_X['InternetService']=='No',0,1)
test_X['MultipleLines']=np.where(test_X['MultipleLines']=='No',0,1)
test_X['Partner']=np.where(test_X['Partner']=='No',0,1)
test_X['PhoneService']=np.where(test_X['PhoneService']=='No',0,1)
test_X['gender']=np.where(test_X['gender']=='No',0,1)

In [52]:
y_pred = knn.predict(test_X)

In [53]:
submit = test_X['ID']

In [56]:
df = pd.DataFrame(columns=['ID','Label'])

In [58]:
df['ID'], df['Label'] = test_X['ID'], y_pred

In [61]:
df['Label']=np.where(df['Label']==0,'No','Yes')

In [62]:
df.to_csv('submit_example.csv', index=False)